version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5433:5432'
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=True
      - ENGINE=django.db.backends.postgresql_psycopg2
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOST=localhost,127.0.0.1,frontend,webapp,0.0.0.0
    depends_on:
      - db
  frontend:
    container_name: front_end
    build:
      context: frontend/
      dockerfile: frontend/deploy.Dockerfile
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - webapp