version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=True
      - ENGINE=django.db.backends.postgresql_psycopg2
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db