# Generated by Django 3.1.7 on 2021-04-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210411_1801'),
        ('backend', '0002_auto_20210411_1800'),
    ]

    operations = [
    ]
