# Generated by Django 3.1.7 on 2021-04-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_uploadrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='upload_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.uploadrequest'),
        ),
    ]
