# Generated by Django 3.1.7 on 2021-04-02 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_uploadrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrequest',
            name='file1',
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
