# Generated by Django 3.1.7 on 2021-05-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210502_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('pesel', 'contest')},
        ),
    ]
