# Generated by Django 3.1.7 on 2021-04-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210417_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='upload_request',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
    ]
