# Generated by Django 3.1.7 on 2021-05-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210502_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentresult',
            options={'ordering': ('points', 'result')},
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='degree',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Master')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='type',
            field=models.CharField(default='stacjonarne', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatedschool',
            name='school_type',
            field=models.CharField(choices=[('T', 'techikum'), ('L', 'liceum'), ('1', 'Bachelor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recruitmentresult',
            name='result',
            field=models.CharField(choices=[('accepted', 'rekrutacja zakończona'), ('signed', 'wpisany'), ('rejected', 'niezakwalifikowany'), ('unregistered', 'nieprzyjęty z powodu niedokonania wpisu')], max_length=100),
        ),
        migrations.CreateModel(
            name='FieldOfStudyPlacesLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('places', models.IntegerField()),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fieldofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudyNextDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fieldofstudy')),
                ('second_degree_field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_degree_field_of_study', to='backend.fieldofstudy')),
            ],
        ),
    ]
