# Generated by Django 3.1.7 on 2021-04-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_merge_20210417_2357'),
        ('backend', '0005_auto_20210418_0144'),
    ]

    operations = [
    ]
