# Generated by Django 3.1.7 on 2021-03-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('register', '0002_auto_20210328_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
