name: deploy_frontend_testing
on:
  push:
    tags:
      - frontend.testing.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: frontend_testing_deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "io-frontend-testing"
          email: tmek1244@wp.pl
          dockerfile_directory: ./frontend
          dockerfile_name: deploy.Dockerfile

