name: deploy_backend_testing
on:
  push:
    tags:
      - backend.testing.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: backend_testing_deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "io-backend-testing"
          email: tmek1244@wp.pl
          dockerfile_directory: ./
          dockerfile_name: backend.Dockerfile
        env:
          ALLOWED_HOST: "https://io-backend-testing.herokuapp.com/"

