name: deploy_frontend_testing
on:
  push:
    tags:
      - frontend.testing.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: frontend_testing_deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        env:
          proxy_name: 'https://io-backend-testing.herokuapp.com'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "io-frontend-testing"
          heroku_email: tmek1244@wp.pl
          usedocker: true
          appdir: frontend
          docker_build_args: |
            proxy_name



