name: PythonCI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv --python python
          pipenv install isort --dev
          pipenv install flake8
          pipenv install mypy
          pipenv install --deploy --dev

      - run: pipenv run isort --recursive --diff .
      - run: pipenv run flake8 .
      - run: pipenv run mypy .
